name: Daily Contribution Streak

on:
  schedule:
    - cron: '30 4 * * *' # Runs daily at 04:30 UTC (10:00 AM IST)
  workflow_dispatch: # Allows manual triggering

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Keep streak alive
        run: |
          date >> streak.txt
          git config --global user.name "sushantisgitting"
          git config --global user.email "pvsksushant@gmail.com"
          git add streak.txt
          git commit -m "chore: keep contribution streak alive [skip ci]"
          git push
